### ISSUE TITLE
Last - First name order in developer registration email confirmation

### ISSUE THREAD

**Issue by rlucia** [teamdigitale/digital-citizenship#123]
I had the chance to register as an API user, and I noticed that in the welcome message I've been named as "Last First" name.

I'm not sure this really is an issue, but giving the highly innovative process you've been put together, I think that Italian PA should call people with their first names, not last names :-)

I'd have liked to receive an email being addressed as "Welcome First Last name"!

**Comment by gunzip** [comment]
thank you, here's the offending line: 
https://github.com/teamdigitale/digital-citizenship-onboarding/blob/master/src/app.ts#L98
I'll change asap

**Comment by rlucia** [comment]
Wonderful, report-to-fix: <1hr!

You r0ck!
